### PR TITLE
Ruby coding style guide

### PR DESCRIPTION
**Pull request by minsikzzang**
Ruby coding style guide

### CODE REVIEW

**Comment by ericescalante** [comment]
Looks good so far. Will you add line length later on?

**Comment by minsikzzang** [comment]
yup, it's WIP

**Comment by willhall88** [comment]
:+1: looks good

**Comment by ericescalante** [comment]
Maybe add some backticks to keywords, etc on description text? Like this one for example:
From:  Indent when as deep as case.
To: Indent `when` as deep as `case`
Makes it a bit easier to read.

**Comment by mike-sheppard** [comment]
looks great :+1: on first read - I'll need to re-read a few times to take it all in though!

**Comment by minsikzzang** [comment]
:+1: thanks for fixing typo @ericescalante

**Comment by ericescalante** [comment]
12.3 and 12.4 have the same body.

**Comment by ericescalante** [comment]
:+1: rock and roll!

**Pull request merged**
